version: "3.1"

services:
  mysql:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@1234
      TZ: Asia/Seoul
    ports:
    - "3306:3306"
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=0  --default-time-zone="+09:00"

networks:
  default:
    external:
      name: mysql
